CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE

SELECT * FROM SEQ;

SELECT * FROM BOARD;
INSERT INTO BOARD 
VALUES(BOARD_SEQ.NEXTVAL, 'T1','C1','test',SYSDATE,0);

SELECT BOARD_SEQ.CURRVAL FROM DUAL;