CREATE TABLE MEMBER (
	MEMBERID VARCHAR2(100) CONSTRAINT MM_ID_PK PRIMARY KEY,
	PASSWORD VARCHAR2(100),
	NAME     VARCHAR2(100),
	PHONENUMBER VARCHAR2(20),
	EMAIL    VARCHAR2(100),
	ADDRESS  VARCHAR2(100)
);

CREATE TABLE ADDRESS (
	ADDRESSNUMBER NUMBER CONSTRAINT ADDRESS_NUMBER_PK PRIMARY KEY,
	MEMBERID VARCHAR2(100), 
	ADDRESS VARCHAR2(100),
	PHONENUMBER VARCHAR2(15),
	NAME VARCHAR2(100),
	CONSTRAINT MEMBER_ID_FK FOREIGN KEY (MEMBERID) REFERENCES MEMBER (MEMBERID) ON DELETE SET NULL --ON DELETE CASCADE 
);

SELECT * FROM MEMBER;
SELECT * FROM ADDRESS;

--CREATE에 바로 넣기보다는 ALTER을 넣어서 제약조건을 만든다---

CREATE TABLE ROLE (
	ROLENUM NUMBER,
	ROLENAME VARCHAR2(100)
);
ALTER TABLE ROLE ADD CONSTRAINT ROLE_PN_PK PRIMARY KEY (ROLENUM);
SELECT * FROM ROLE;


CREATE TABLE MEMBERROLE(
	MEMBERID VARCHAR2(200),
	ROLENUM NUMBER
);

SELECT * FROM MEMBERROLE;
ALTER TABLE MEMBERROLE RENAME COLUMN ID TO MEMBERID;

ALTER TABLE MEMBERROLE ADD CONSTRAINT MM_ID_FK FOREIGN KEY (MEMBERID) REFERENCES MEMBER (MEMBERID);
ALTER TABLE MEMBERROLE ADD CONSTRAINT MB_RN_FK FOREIGN KEY (ROLENUM) REFERENCES ROLE (ROLENUM);
ALTER TABLE MEMBERROLE ADD CONSTRAINT MR_PK PRIMARY KEY (MEMBERID, ROLENUM);

INSERT INTO MEMBER
VALUES (2,2,'2','2','2','2');

INSERT INTO ROLE 
VALUES (2,'Admin2');

INSERT INTO MEMBERROLE 
VALUES ('1', 1);