CREATE SEQUENCE ROLE_NUM_SEQ;
CREATE SEQUENCE PRODUCT_ID_SEQ;
CREATE SEQUENCE RECORD_NUM_SEQ;
CREATE SEQUENCE LOAN_ID_SEQ;
CREATE SEQUENCE CARD_RECORD_ID_SEQ;
	

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR(50),
	MEMBER_PW VARCHAR(100),
	MEMBER_NAME VARCHAR(50),
	MEMBER_ADDRESS VARCHAR(200),
	MEMBER_PHONE VARCHAR(20),
	MEMBER_EMAIL VARCHAR(100)
);
ALTER TABLE MEMBER ADD CONSTRAINT MM_ID_PK PRIMARY KEY (MEMBER_ID);
ALTER TABLE MEMBER MODIFY MEMBER_PW NOT NULL;
ALTER TABLE MEMBER MODIFY MEMBER_NAME NOT NULL;
ALTER TABLE MEMBER MODIFY MEMBER_ADDRESS NOT NULL;
ALTER TABLE MEMBER ADD CONSTRAINT MM_PHONE_U UNIQUE (MEMBER_PHONE);
ALTER TABLE MEMBER ADD CONSTRAINT MM_EMAIL_U UNIQUE (MEMBER_EMAIL);

INSERT INTO MEMBER 
VALUES ('Admin','admin','안녕','djhfd','010-111-1111','djfld@naver.com');

SELECT * FROM MEMBER;


CREATE TABLE MEMBER_ROLE(
	ROLE_NUM NUMBER,
	MEMBER_ID VARCHAR(50)
);

ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MR_RN_FK FOREIGN KEY (ROLE_NUM) REFERENCES ROLE (ROLE_NUM); 
ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MR_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

INSERT INTO MEMBER_ROLE 
VALUES (9, 'Admin');

SELECT * FROM MEMBER_ROLE;

CREATE TABLE ROLE(
	ROLE_NUM NUMBER,
	ROLE_NAME VARCHAR(100)
);

ALTER TABLE ROLE ADD CONSTRAINT ROLE_RN_PK PRIMARY KEY (ROLE_NUM); 

INSERT INTO ROLE
VALUES (ROLE_NUM_SEQ.NEXTVAL, 'Grant name');

SELECT * FROM ROLE;

CREATE TABLE BANK_BOOK (
	ACCOUNT_NUM NUMBER,
	MEMBER_ID VARCHAR(50),
	PRODUCT_ID NUMBER,
	NAME VARCHAR(50),
	ACCOUNT_OPEN_DATE DATE,
	ACCOUNT_EXTRIA NUMBER,
	ACCOUNT_PW NUMBER(10)
);

ALTER TABLE BANK_BOOK ADD CONSTRAINT BB_NUM_PK PRIMARY KEY(ACCOUNT_NUM);
ALTER TABLE BANK_BOOK ADD CONSTRAINT BB_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);
ALTER TABLE BANK_BOOK ADD CONSTRAINT BB_PD_FK FOREIGN KEY (PRODUCT_ID) REFERENCES BOOK_PRODUCT (PRODUCT_ID);
ALTER TABLE BANK_BOOK MODIFY ACCOUNT_PW NOT NULL;
ALTER TABLE BANK_BOOK MODIFY NAME NOT NULL;
ALTER TABLE BANK_BOOK MODIFY ACCOUNT_OPEN_DATE NOT NULL;
ALTER TABLE BANK_BOOK MODIFY ACCOUNT_EXTRIA NOT NULL;

INSERT INTO BANK_BOOK 
VALUES (110,'Admin',3,'아아아안녕','2023-1-27',10000,0);

SELECT * FROM BANK_BOOK;

CREATE TABLE LOAN_MEMBER (
	MEMBER_ID VARCHAR(50),
	LOAN_ID NUMBER,
	LOAN_AMOUNT NUMBER
);

ALTER TABLE LOAN_MEMBER ADD CONSTRAINT LM_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);
ALTER TABLE LOAN_MEMBER ADD CONSTRAINT LM_LD_FK FOREIGN KEY (LOAN_ID) REFERENCES LOAN_PRODUCT (LOAN_ID);
ALTER TABLE LOAN_MEMBER MODIFY LOAN_AMOUNT NOT NULL;
INSERT INTO LOAN_MEMBER 
VALUES ('Admin',1,10000);

SELECT * FROM LOAN_MEMBER;

CREATE TABLE LOAN_PRODUCT (
	LOAN_ID NUMBER,
	LOAN_NAME VARCHAR(100),
	LOAN_LIMIT NUMBER,
	LOAN_INTERTEST NUMBER(2,1),
	LOAN_DETAIL CLOB
);

ALTER TABLE LOAN_PRODUCT ADD CONSTRAINT LOAN_ID_PK PRIMARY KEY(LOAN_ID);
ALTER TABLE LOAN_PRODUCT MODIFY LOAN_NAME NOT NULL;
ALTER TABLE LOAN_PRODUCT MODIFY LOAN_LIMIT NOT NULL;
ALTER TABLE LOAN_PRODUCT MODIFY LOAN_INTERTEST NOT NULL;
INSERT INTO LOAN_PRODUCT 
VALUES (LOAN_ID_SEQ.NEXTVAL, '카카오',20000,2.5,'대출입니다');

SELECT * FROM LOAN_PRODUCT;

CREATE TABLE BOOK_PRODUCT(
	PRODUCT_ID NUMBER,
	PRODUCT_NAME VARCHAR(100),
	PRODUCT_INTERTEST NUMBER(2,1),
	PRODUCT_IS_SELL NUMBER(2),
	PRODUCT_DETAIL CLOB,
	PRODUCT_CONDITION CLOB,
	PRODUCT_TRANSFER_LIMIT NUMBER
);

ALTER TABLE BOOK_PRODUCT ADD CONSTRAINT BP_ID_PK PRIMARY KEY (PRODUCT_ID);
ALTER TABLE BOOK_PRODUCT ADD CONSTRAINT BP_NAME_U UNIQUE (PRODUCT_NAME);
ALTER TABLE BOOK_PRODUCT MODIFY PRODUCT_INTERTEST NOT NULL;
ALTER TABLE BOOK_PRODUCT MODIFY PRODUCT_IS_SELL NOT NULL;
ALTER TABLE BOOK_PRODUCT MODIFY PRODUCT_CONDITION NOT NULL;

INSERT INTO BOOK_PRODUCT 
VALUES (PRODUCT_ID_SEQ.NEXTVAL,'아아아안녕',3.1,20,'합니다','조건은 0세 이상입니다',30000 );

SELECT * FROM BOOK_PRODUCT;

CREATE TABLE RECORD(
	RECORD_NUM NUMBER,
	ACCOUNT_NUM NUMBER,
	TRANSFER_TYPE VARCHAR(50),
	TRANSFER_AMMOUNT NUMBER,
	SEND_ACCOUNT_NUM NUMBER,
	RECEPT_ACCOUNT_NUM NUMBER,
	SENDER_NAME VARCHAR(50),
	TRANSFER_DATE DATE
);

ALTER TABLE RECORD ADD CONSTRAINT RC_NUM_PK PRIMARY KEY (RECORD_NUM);
ALTER TABLE RECORD ADD CONSTRAINT RC_NUM_FK FOREIGN KEY (ACCOUNT_NUM) REFERENCES BANK_BOOK (ACCOUNT_NUM);
ALTER TABLE RECORD MODIFY TRANSFER_TYPE NOT NULL;ㄴㄴㄴ
ALTER TABLE RECORD RENAME COLUMN TRANSFER_AMMOUNT TO TRANSFER_ACCOUNT;
ALTER TABLE RECORD RENAME COLUMN TRANSFER_ACCOUNT TO TRANSFER_AMOUNT;
ALTER TABLE RECORD MODIFY TRANSFER_ACCOUNT NOT NULL;
ALTER TABLE RECORD MODIFY SEND_ACCOUNT_NUM NOT NULL;
ALTER TABLE RECORD MODIFY RECEPT_ACCOUNT_NUM NOT NULL;
ALTER TABLE RECORD MODIFY SENDER_NAME NOT NULL;
ALTER TABLE RECORD MODIFY TRANSFER_DATE NOT NULL;

INSERT INTO RECORD 
VALUES (RECORD_NUM_SEQ.NEXTVAL,110,'돈',1500, )


CREATE TABLE CARD (
	CARD_NUM NUMBER,
	ACCOUNT_NUM NUMBER,
	CARD_NAME VARCHAR(100),
	CARD_TYPE VARCHAR(50),
	CARD_LIMIT NUMBER,
	ACCOUNT_PW NUMBER(10),
	CARD_PW NUMBER(10)
);

ALTER TABLE CARD ADD CONSTRAINT CARD_NUM_PK PRIMARY KEY (CARD_NUM);
ALTER TABLE CARD ADD CONSTRAINT CARD_NUM_FK FOREIGN KEY (ACCOUNT_NUM) REFERENCES BANK_BOOK (ACCOUNT_NUM);
ALTER TABLE CARD MODIFY CARD_NAME NOT NULL;
ALTER TABLE CARD MODIFY CARD_TYPE NOT NULL;
ALTER TABLE CARD MODIFY ACCOUNT_PW NOT NULL;
ALTER TABLE CARD MODIFY CARD_PW NOT NULL;

CREATE TABLE CARD_RECORD (
	CARD_RECORD_ID NUMBER,
	CARD_NUM NUMBER,
	USED_AMOUNT NUMBER,
	CARD_RECORD_DATE DATE,
	CARD_WHERE_USED VARCHAR(100)
);

ALTER TABLE CARD_RECORD ADD CONSTRAINT CR_ID_PK PRIMARY KEY (CARD_RECORD_ID);
ALTER TABLE CARD_RECORD ADD CONSTRAINT CR_NUM_FK FOREIGN KEY (CARD_NUM) REFERENCES CARD (CARD_NUM);
ALTER TABLE CARD_RECORD MODIFY USED_AMOUNT NOT NULL;
ALTER TABLE CARD_RECORD MODIFY CARD_RECORD_DATE NOT NULL;
ALTER TABLE CARD_RECORD MODIFY CARD_WHERE_USED NOT NULL;