CREATE TABLE PRODUCT(
	PRODUCT_NUM NUMBER CONSTRAINT PRODUCT_NUM_PK PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(200),
	PRODUCT_DETAIL CLOB,
	PRODUCT_JUMSU NUMBER(2,1)
);
SELECT* FROM PRODUCT;

CREATE TABLE PRODUCTOPTION(
	OPTION_NUM NUMBER CONSTRAINT OPTION_NUM_PK PRIMARY KEY,
	PRODUCT_NUM NUMBER,
	OPTION_NAME VARCHAR2(200),
	OPTION_PRICE NUMBER(7),
	OPTION_STOCK NUMBER(7),
	CONSTRAINT OPTION_NUM_FK FOREIGN KEY (PRODUCT_NUM) REFERENCES PRODUCT (PRODUCT_NUM) ON DELETE SET NULL
);

SELECT*FROM PRODUCTOPTION;

CREATE TABLE COMMENT_1(
	COMMENT_NUM NUMBER CONSTRAINT COMMENT_NUM_PK PRIMARY KEY,
	PRODUCT_NUM NUMBER,
	MEMBER_ID VARCHAR2(100),
	COMMENT_JUMSU NUMBER(2,1),
	COMMENT_DATE DATE,
	COMMENT_WRITER VARCHAR2(100),
	COMMENT_COMMENT CLOB,
	CONSTRAINT COMMENT_NUM_FK FOREIGN KEY (PRODUCT_NUM) REFERENCES PRODUCT (PRODUCT_NUM) ON DELETE SET NULL,
	CONSTRAINT COMMENT_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL
);

SELECT*FROM COMMENT_1;

SELECT * FROM MEMBER;

CREATE SEQUENCE PRODUCT_SEQ;

INSERT INTO PRODUCT 
VALUES(PRODUCT_SEQ.NEXTVAL, '옷','옷입니다',4.3);

INSERT INTO PRODUCT
VALUES (PRODUCT_SEQ.NEXTVAL,'신발','신발입니다',3.8);

INSERT INTO COMMENT_1
VALUES(PRODUCT_SEQ.NEXTVAL,1,NULL,4.1,SYSDATE,'WRITER','HFKDJSHFKJDHKFJKHDFD');
