--회원가입
-- 이름, 아이디, 패스워드, 전화번호, 이메일, 나이 

--------이건 좋은 방법이 아니다------------
CREATE TABLE MEMBER(
	ID VARCHAR2(50) PRIMARY KEY,
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) UNIQUE, --NULL은 중복이 아니다
	EMAIL VARCHAR2(100),
	AGE NUMBER(3) CHECK (AGE BETWEEN 0 AND 150)
);

INSERT INTO MEMBER(ID,PW,NAME,PHONE,EMAIL,AGE)
	VALUES ('test','test','test','010-111-1111','test@naver.com',30);

INSERT INTO MEMBER(ID,PW,NAME,PHONE,EMAIL,AGE)
	VALUES ('test1','test','test',NULL,NULL,30);

INSERT INTO MEMBER(ID,PW,NAME,PHONE,EMAIL,AGE)
	VALUES ('test2','test','test','010-222-2222',NULL,20);
		
SELECT * FROM MEMBER;

DROP TABLE MEMBER;

TRUNCATE TABLE MEMBER;
--테이블 자체 삭제 아닌 데이터만 삭제--

SELECT * FROM USER_CONSTRAINTS;

--1. Column 레벨 방식---
CREATE TABLE MEMBER(
	ID VARCHAR2(50) CONSTRAINT MEMBER_ID_PK PRIMARY KEY, 
	PW VARCHAR2(50) CONSTRAINT MBMBER_PW_NN NOT NULL, 
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) CONSTRAINT MEMBER_PHONE_U UNIQUE, 
	EMAIL VARCHAR2(100) CONSTRAINT MEMBER_EMAIL_U UNIQUE,
	AGE NUMBER(3) CHECK (AGE BETWEEN 0 AND 150)
);

--2. TABLE 레벨 방식 ---
CREATE TABLE MEMBER(
	ID VARCHAR2(50) , 
	PW VARCHAR2(50) , 
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50), 
	EMAIL VARCHAR2(100),
	AGE NUMBER(3),
	CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID),
	CONSTRAINT MEMBER_PHONE_U UNIQUE(PHONE)
);

CREATE TABLE BOARD (
	NUM NUMBER CONSTRAINT BOARD_NUM_PK PRIMARY KEY,
	TITLE VARCHAR2(200),
	CONTENTS CLOB,  --얼마를 담아야하는지 안적음
	WRITER VARCHAR2(50), --CONSTRAINT BOARD_W_FK REFERENCES MEMBER (ID), --ID와 동일하게 맞춤
	REGDATE DATE,
	HIT NUMBER
	--CONSTRAINT BOARD_W_FK FOREIGN KEY (WRITER) REFERENCES MEMBER (ID) ON DELETE SET NULL --ON DELETE CASCADE 
	                                                                     --참조된 부모 테이블이 삭제 되었을 때 참조하는 부모 테이블의 컬럼이 NULL로 바뀐다
);

ALTER TABLE BOARD ADD CONSTRAINT BOARD_ID_FK FOREIGN KEY (WRITER) REFERENCES MEMBER (ID) ON DELETE SET NULL;

INSERT INTO BOARD 
VALUES(1,'T1','C1','W1',SYSDATE,0);

DELETE MEMBER WHERE ID='test1';
DELETE MEMBER WHERE ID='test';
DELETE MEMBER;
DELETE BOARD WHERE NUM = 1;

DROP TABLE BOARD;

SELECT * FROM BOARD;

INSERT INTO ADDRESS 
VALUES('안녕','010-111-1111','hfkdh@naver.com',1);

SELECT * FROM ADDRESS;

DROP TABLE ADDRESS;

SELECT * FROM RECYCLEBIN;  
PURGE RECYCLEBIN;   
FLASHBACK TABLE MEMBER TO BEFORE DROP;

-------------------------------------------------
SELECT * FROM MEMBER;
DROP TABLE MEMBER;

ALTER TABLE "MEMBER" ADD (BIRTH DATE);
ALTER TABLE "MEMBER" DROP COLUMN BIRTH;
ALTER TABLE "MEMBER" RENAME COLUMN ID TO USER_ID;

UPDATE MEMBER SET PHONE = NULL;
ALTER TABLE "MEMBER" MODIFY (PHONE NUMBER);

ALTER TABLE MEMBER DROP CONSTRAINT MEMBER_PHONE_U;
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PHONE_U UNIQUE (PHONE);
SELECT * FROM USER_CONSTRAINTS; --CONSTRAINT_TYPE 확인--

RENAME MEMBER TO USERS;
RENAME USERS TO MEMBER;
SELECT * FROM USERS;

