CREATE TABLE MEMBER (
	MEMBERID VARCHAR2(100) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PASSWORD VARCHAR2(100),
	NAME     VARCHAR2(100),
	PHONENUMBER VARCHAR2(20),
	EMAIL    VARCHAR2(100),
	ADDRESS  VARCHAR2(100)
);

CREATE TABLE ADDRESS (
	ADDRESSNUMBER NUMBER CONSTRAINT ADDRESS_NUMBER_PK PRIMARY KEY,
	MEMBERID VARCHAR2(100), 
	ADDRESS VARCHAR2(100),
	PHONENUMBER VARCHAR2(15),
	NAME VARCHAR2(100),
	CONSTRAINT MEMBER_ID_FK FOREIGN KEY (MEMBERID) REFERENCES MEMBER (MEMBERID) ON DELETE SET NULL --ON DELETE CASCADE 
);

SELECT * FROM MEMBER;
SELECT * FROM ADDRESS;

CREATE SEQUENCE 