--1.사번이 198인 사원이 근무하는 부서가 있는 도시가 속해있는 나라가 있는 대륙 정보

SELECT REGION_NAME 
FROM REGIONS r
WHERE REGION_ID = 
	(SELECT REGION_ID 
	FROM COUNTRIES c 
	WHERE COUNTRY_ID =
		(SELECT COUNTRY_ID 
		FROM LOCATIONS l
		WHERE LOCATION_ID =
			(SELECT LOCATION_ID 
			FROM DEPARTMENTS d
			WHERE DEPARTMENT_ID = 
				(SELECT DEPARTMENT_ID  
				FROM EMPLOYEES E
				WHERE EMPLOYEE_ID = 198
				)
			)
		)
	);	

--2.LAST_NAME이 Khoo인 사람의 근무하는 부서명

SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS d 
WHERE DEPARTMENT_ID = 
	(SELECT DEPARTMENT_ID 
	FROM EMPLOYEES e 
	WHERE LAST_NAME = 'Khoo');

--3.사원번호가 199인 사원의 매니저가 근무하는 부서가 있는 나라명 출력

SELECT COUNTRY_NAME 
FROM COUNTRIES c 
WHERE COUNTRY_ID IN
	(SELECT COUNTRY_ID 
	FROM LOCATIONS l
	WHERE LOCATION_ID IN
		(SELECT LOCATION_ID 
		FROM DEPARTMENTS d 
		WHERE DEPARTMENT_ID IN
			(SELECT DEPARTMENT_ID 
			FROM EMPLOYEES e 
			WHERE MANAGER_ID IN
				(SELECT MANAGER_ID 
				FROM EMPLOYEES
				WHERE EMPLOYEE_ID = 199)
			)
		)
	);	

--4.사원들 중에서 월급이 가장 적은 사원이 근무하는 도시명

SELECT CITY 
FROM LOCATIONS l
WHERE LOCATION_ID IN
	(SELECT LOCATION_ID 
	FROM DEPARTMENTS d 
	WHERE DEPARTMENT_ID IN 
		(SELECT DEPARTMENT_ID  
		FROM EMPLOYEES 
		WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES e )
		)
	);
--5. 부서명이 IT인 부서에 근무하는 사원들의 모든 정보 출력

SELECT *
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 
	(SELECT DEPARTMENT_ID 
	FROM DEPARTMENTS d 
	WHERE DEPARTMENT_NAME = 'IT');

--6. Employees 테이블에서 LAST_NAME이 Greenberg 사원보다 급여를 더 많이 받고 있는 사원들정보 출력
